# Generated by Django 4.1.6 on 2024-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_ip", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_device",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user_id",
                    models.BigIntegerField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
