# Generated by Django 4.1.6 on 2024-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
